"""Add manual creation fields to topology service

Revision ID: add_manual_creation
Revises: 1c117f1accff
Create Date: 2024-12-25 01:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'add_manual_creation'
down_revision = '1c117f1accff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologyservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=True, server_default='true'))

    # Set is_manual=false and is_editable=false for existing provider-sourced services
    op.execute("""
        UPDATE topologyservice 
        SET is_manual = false, is_editable = false 
        WHERE source_provider_id != 'unknown'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topologyservice', schema=None) as batch_op:
        batch_op.drop_column('is_editable')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_manual')
    # ### end Alembic commands ### 